ARG version
FROM almalinux:${version:-9}
ENV COURSE="docker" \
    TRAINER="siva"
ARG TIME="9HR" 
ENV TIME=$TIME
RUN echo "I am learning ${COURSE}, trainer is ${TRAINER} and total time is ${TIME}"   
CMD ["sleep", "1000"]