FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/Masthantech/ansible/refs/heads/main/03-nginx-ins.yaml /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
ADD smaple-1.tar /tmp/
CMD ["nginx", "-g" ,"daemon off;" ]